### ISSUE TITLE
Default view option is fixed with `Unified` when using chrome extension

### ISSUE THREAD

**Issue by lntuition** [berzniz/github_pr_tree#151]
Hello, first thank you for maintaining good project 👍 

I'm now using [Better Pull Requests for GitHub for Chrome](https://chrome.google.com/webstore/detail/better-pull-request-for-g/nfhdjopbhlggibjlimhdbogflgmbiahc). I found that view option is fixed with `Unified` option when i first visit any PR page (So i always need to change option to `Split` and do `apply and reload` when i first visit PR page) with chrome extension. Could you check this issue plz? 😄 

My environment is like below
- Chrome browser version : 90.0.4430.85
- Mac os version : macOS Catalina 10.15.7

**Comment by berzniz** [comment]
HI @lntuition — I can't seem to reproduce this. If anyone can reproduce this and provide a PR fix, let's open this again.

**Comment by cdavie-weconnect** [comment]
I am also seeing this behavior — worse, in fact, because even when I change the URL manually to add `?diff=unified`, I get redirected back to split.

**Comment by berzniz** [comment]
Hi @cdavie-weconnect, can you please verify that this is caused by this extension?

Here's what I suggest:
1. Remove the extension from Chrome
2. Check if the problem persists
3. If it does persist - it is not this extension that is causing it

If it happens only when the extension is on:
1. Please disable all other extensions temporarily
2. Check if the problem persists

I am not able to reproduce, if we can get steps for reproduction, we can handle it
