### ISSUE TITLE
[feature request] filter out viewed files

### ISSUE THREAD

**Issue by kopach** [berzniz/github_pr_tree#162]
Would be great to hide files marked as "viewed" in tree view. This way, the user could focus on unreviewed files only

**Comment by berzniz** [comment]
Thanks for the feedback. This changes a lot in how GitHub works and I think it is out of the scope of this extension. You can collapse files in GitHub today (it automatically happens when clicking "Viewed") and it provides a similar solution.

What I would consider is a "single file" mode similar to what we see in IDEs.

**Comment by eli-s-r** [comment]
@berzniz would you consider adding a toggle on the right of the filter field to hide files that have been marked as viewed? I sometimes work with PRs with over 100 changed files and this would be super helpful since even the collapsing GitHub does adds up in space. I would be happy to make a PR for this, but I understand if you don't think it's in scope. Thanks!

**Comment by kopach** [comment]
This is actually not something very complex to implement. I have done some changes myself locally, and it works fine for me. I'll try to push those in the nearest future

**Comment by eli-s-r** [comment]
Thanks @kopach! Much appreciated
